In [2]:
import pandas as pd 
import numpy as np

In [3]:
file_path_customers = r"C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\raw\customers.csv"
customers_df = pd.read_csv(file_path_customers)

In [4]:
file_path_orders = r"C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\raw\orders.csv"
orders_df = pd.read_csv(file_path_orders)

In [5]:
file_path_order_items = r"C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\raw\order_items.csv"
order_items_df= pd.read_csv(file_path_order_items)

In [6]:
file_path_products = r"C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\raw\products.csv"
products_df= pd.read_csv(file_path_products)

In [7]:
customers_df .head()

   customer_id signup_date state acquisition_channel
0            1  2024-09-13    CO      organic_search
1            2  2025-10-21    IL         paid_search
2            3  2025-01-17    AZ            referral
3            4  2024-06-23    FL         paid_social
4            5  2025-04-08    IL         paid_social

In [8]:
print(f"shape : {customers_df .shape}")
print("\n")
customers_df .info()
print("\n")

print("\n")
customers_df .isnull().sum()

shape : (3600, 4)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          3600 non-null   int64
 1   signup_date          3600 non-null   object
 2   state                3600 non-null   object
 3   acquisition_channel  3600 non-null   object
dtypes: int64(1), object(3)
memory usage: 112.6+ KB

customer_id            0
signup_date            0
state                  0
acquisition_channel    0
dtype: int64

In [9]:
customers_df .describe()

       customer_id
count  3600.000000
mean   1800.500000
std    1039.374812
min       1.000000
25%     900.750000
50%    1800.500000
75%    2700.250000
max    3600.000000

In [10]:
customers_df ['signup_date'] = pd.to_datetime(customers_df ['signup_date'])

In [11]:
customers_df .dtypes

customer_id                     int64
signup_date            datetime64[ns]
state                          object
acquisition_channel            object
dtype: object

In [12]:
customers_df [['state','acquisition_channel']] = customers_df [['state','acquisition_channel']].astype("string")

In [13]:
customers_df .duplicated().value_counts()

False    3600
Name: count, dtype: int64

In [14]:
customers_df ['state'].unique()

<StringArray>
['CO', 'IL', 'AZ', 'FL', 'OH', 'TX', 'WA', 'SC', 'CA', 'NY', 'UT', 'LA', 'PA',
 'GA', 'MD', 'KS', 'OK', 'MO', 'IA', 'NJ', 'MI', 'VA', 'IN', 'CT', 'MN', 'OR',
 'NM', 'NC', 'TN', 'KY', 'NV', 'MA', 'AL', 'WI', 'AR']
Length: 35, dtype: string

In [71]:
customers_df['acquisition_channel'].unique()

<StringArray>
['organic_search',    'paid_search',       'referral',    'paid_social',
      'affiliate',          'email']
Length: 6, dtype: string

# ORDERS

In [15]:
orders_df.head()

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee
0,100001,1530,2024-01-01 09:24:45,completed,credit_card,NaN,6.95
1,100002,3531,2024-01-01 10:37:49,completed,credit_card,NaN,0.00
2,100003,840,2024-01-01 10:59:09,completed,credit_card,NaN,0.00
3,100004,725,2024-01-01 12:48:34,completed,apple_pay,WELCOME10,0.00
4,100005,3452,2024-01-01 17:44:03,completed,gift_card,NaN,0.00

In [72]:
orders_df.shape

(9207, 7)

In [69]:
orders_df['status'].value_counts()

status
completed    8456
returned      407
canceled      344
Name: count, dtype: int64

In [70]:
orders_df['payment_method'].unique()

array(['credit_card', 'apple_pay', 'gift_card', 'paypal'], dtype=object)

In [16]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9245 entries, 0 to 9244
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        9245 non-null   int64
 1   customer_id     9245 non-null   int64
 2   order_date      9245 non-null   object
 3   status          9245 non-null   object
 4   payment_method  9245 non-null   object
 5   discount_code   1411 non-null   object
 6   shipping_fee    9245 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 505.7+ KB

In [17]:
orders_df.isnull().sum()

order_id             0
customer_id          0
order_date           0
status               0
payment_method       0
discount_code     7834
shipping_fee         0
dtype: int64

In [18]:
orders_df['discount_code'] = orders_df['discount_code'].fillna("NO DISCOUNT")

In [19]:
orders_df['discount_code']

0       NO DISCOUNT
1       NO DISCOUNT
2       NO DISCOUNT
3         WELCOME10
4       NO DISCOUNT
           ...
9240      HOLIDAY20
9241      HOLIDAY20
9242    NO DISCOUNT
9243    NO DISCOUNT
9244      HOLIDAY20
Name: discount_code, Length: 9245, dtype: object

In [20]:
orders_df['status'].unique()

array(['completed', 'returned', 'canceled'], dtype=object)

In [21]:
orders_df['order_date'] = pd.to_datetime(orders_df['order_date'])

In [22]:
orders_df.dtypes

order_id                   int64
customer_id                int64
order_date        datetime64[ns]
status                    object
payment_method            object
discount_code             object
shipping_fee             float64
dtype: object

In [23]:
orders_df['shipping_fee']

0       6.95
1       0.00
2       0.00
3       0.00
4       0.00
        ...
9240    6.95
9241    0.00
9242    0.00
9243    6.95
9244    0.00
Name: shipping_fee, Length: 9245, dtype: float64

In [24]:
orders_df.duplicated().value_counts()

False    9207
True       38
Name: count, dtype: int64

In [25]:
orders_df.shape

(9245, 7)

In [26]:
orders_df = orders_df.drop_duplicates()

In [27]:
orders_df.shape

(9207, 7)

# order_items

In [28]:
order_items_df.head()

   order_id  product_id  quantity  unit_price  discount_amount
0    100001        1031         1       38.99              0.0
1    100002        1087         1       45.99              0.0
2    100002        1072         1      141.99              0.0
3    100003        1048         1      139.99              0.0
4    100004        1083         1       19.99              2.0

In [29]:
order_items_df.shape

(15608, 5)

In [30]:
order_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15608 entries, 0 to 15607
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         15608 non-null  int64
 1   product_id       15608 non-null  int64
 2   quantity         15608 non-null  int64
 3   unit_price       15409 non-null  float64
 4   discount_amount  15608 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 609.8 KB

In [31]:
order_items_df.isnull().sum()

order_id             0
product_id           0
quantity             0
unit_price         199
discount_amount      0
dtype: int64

In [32]:
order_items_df.describe()

,order_id,product_id,quantity,unit_price,discount_amount
count,15608.000000,15608.000000,15608.000000,15409.000000,15608.000000
mean,104570.429011,1046.471040,1.244810,113.084088,3.201492
std,2659.674531,28.278148,0.577641,108.590935,11.154638
min,100001.000000,1001.000000,1.000000,7.990000,0.000000
25%,102269.750000,1020.000000,1.000000,49.990000,0.000000
50%,104554.500000,1048.000000,1.000000,86.090000,0.000000
75%,106867.250000,1073.000000,1.000000,141.740000,0.000000
max,109207.000000,1090.000000,4.000000,812.690000,196.560000

In [33]:
order_items_df['unit_price'] = order_items_df['unit_price'].fillna(order_items_df['unit_price'])

In [34]:
null_unit_price_pid =  order_items_df[order_items_df.isna().any(axis=1)]['product_id']

In [35]:
null_unit_price_pid

55       1086
110      1020
197      1087
366      1014
626      1077
         ...
15205    1088
15228    1071
15326    1083
15354    1074
15504    1082
Name: product_id, Length: 199, dtype: int64

In [36]:
null_unit_price_pid.value_counts()

product_id
1070    8
1015    5
1060    5
1074    5
1006    5
       ..
1043    1
1064    1
1044    1
1067    1
1001    1
Name: count, Length: 78, dtype: int64

In [37]:
order_items_df[order_items_df['product_id']==1070]

       order_id  product_id  quantity  unit_price  discount_amount
83       100046        1070         1      122.99             0.00
319      100185        1070         4      122.99             0.00
437      100257        1070         3      122.99             0.00
466      100275        1070         1      122.99             0.00
486      100286        1070         1      122.99             0.00
...         ...         ...       ...         ...              ...
15432    109088        1070         1      129.14             0.00
15485    109123        1070         1      129.14            25.83
15555    109172        1070         3      129.14            77.48
15587    109194        1070         1      129.14            12.91
15603    109204        1070         1      129.14            25.83

[238 rows x 5 columns]

In [38]:
products_df[products_df['product_id'] == 1070]

    product_id           product_name category  list_price  unit_cost
69        1070  Stoneware Wall Mirror    Decor      122.99      51.74

In [39]:
# Un products ki list jinki kisi row me unit_price khali hai
null_pids = order_items_df.loc[order_items_df['unit_price'].isna(), 'product_id'].unique()

# Pehla product chuno
pid = null_pids[0]

In [46]:
# Us product ki rows, jahan price bhari hai
sample = order_items_df[(order_items_df['product_id'] == pid) & (order_items_df['unit_price'].notna())]

# list_price aur order_date saath me jodo (VLOOKUP jaisa)
sample = sample.merge(products_df[['product_id', 'list_price']], on='product_id', how='left')
sample = sample.merge(orders_df[['order_id', 'order_date']], on='order_id', how='left')

print(sample[['order_id', 'order_date', 'unit_price', 'list_price', 'discount_amount']].sort_values('order_date'))
print(sample['unit_price'].value_counts())

     order_id          order_date  unit_price  list_price  discount_amount
0      100032 2024-01-05 09:51:41       97.99       97.99             0.00
1      100033 2024-01-05 10:24:31      102.89       97.99             0.00
2      100035 2024-01-05 13:26:36       97.99       97.99             0.00
3      100285 2024-01-31 19:17:04       97.99       97.99             0.00
4      100286 2024-01-31 19:51:37       97.99       97.99             0.00
..        ...                 ...         ...         ...              ...
202    108826 2025-12-07 14:19:29      102.89       97.99             0.00
203    109090 2025-12-22 11:16:05      102.89       97.99             0.00
204    109098 2025-12-22 16:12:03      102.89       97.99             0.00
205    109113 2025-12-23 18:57:48      102.89       97.99            20.58
206    109180 2025-12-29 17:52:07      102.89       97.99            20.58

[207 rows x 5 columns]
unit_price
102.89    122
97.99      85
Name: count, dtype: int64

In [54]:
raw = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\raw\order_items.csv") 
filled_rows = raw['unit_price'].isna()

In [55]:
chk = order_items_df[filled_rows].merge(
    products_df[['product_id', 'list_price']], on='product_id', how='left')

chk['ratio'] = chk['unit_price'] / chk['list_price']
print(chk['ratio'].describe())

count    199.000000
mean       1.035686
std        0.022666
min        1.000000
25%        1.000000
50%        1.050004
75%        1.050009
max        1.050063
Name: ratio, dtype: float64

In [56]:
vc = raw.dropna(subset=['unit_price']).groupby('product_id')['unit_price'].value_counts()
top2 = vc.groupby('product_id').nlargest(2)
print(top2.head(20))

product_id  product_id  unit_price
1001        1001        61.99         111
                        65.09         108
1002        1002        145.94        112
                        138.99         89
1003        1003        24.14         123
                        22.99          89
1004        1004        79.79         108
                        75.99          83
1005        1005        83.99         127
                        79.99          80
1006        1006        17.84         143
                        16.99          83
1007        1007        71.99         111
                        75.59         100
1008        1008        46.19         120
                        43.99          95
1009        1009        131.99        111
                        138.59        110
1010        1010        101.84        117
                        96.99         104
Name: count, dtype: int64

# products

In [61]:
products_df.head()

   product_id            product_name  category  list_price  unit_cost
0        1001        Brass Chef Knife   Kitchen       61.99      38.13
1        1002    Walnut Cutting Board   Kitchen      138.99      74.76
2        1003  Matte Black Dutch Oven   Kitchen       22.99      13.50
3        1004         Classic Skillet   Kitchen       75.99      39.86
4        1005   Linen Mixing Bowl Set  Kitchen        79.99      41.11

In [62]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    90 non-null     int64
 1   product_name  90 non-null     object
 2   category      90 non-null     object
 3   list_price    90 non-null     float64
 4   unit_cost     90 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 3.6+ KB

In [63]:
products_df.duplicated().value_counts()

False    90
Name: count, dtype: int64

In [64]:
products_df['category'].unique()

array(['Kitchen', ' Kitchen', 'Kitchen ', 'kitchen', 'KITCHEN',
       ' Bedding', 'Bedding', 'bedding', 'BEDDING', 'Bath', 'bath',
       'Furniture', 'Furniture ', 'furniture', 'FURNITURE', 'Lighting',
       'LIGHTING', 'Outdoor', 'OUTDOOR', ' Outdoor', 'Decor', 'decor',
       'Storage', 'Storage '], dtype=object)

In [65]:
products_df["category"] = products_df["category"].str.strip().str.title()

In [67]:
products_df['category'].unique()

array(['Kitchen', 'Bedding', 'Bath', 'Furniture', 'Lighting', 'Outdoor',
       'Decor', 'Storage'], dtype=object)

In [80]:
products_df.to_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\cleaned_products.csv', index=False)

In [81]:
customers_df.to_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\cleaned_customers.csv', index=False)

In [82]:
orders_df.to_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\cleaned_orders.csv', index=False)

In [83]:
order_items_df.to_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\cleaned_order_items.csv', index=False)

# MASTER TABLE

In [85]:
cleaned_customers = pd.read_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\cleaned_customers.csv')

In [87]:
cleaned_orders = pd.read_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\cleaned_orders.csv')
cleaned_order_items = pd.read_csv(r'C:/Users/ASUS/OneDrive/Desktop/izaan_coding/project/customer-retention-analysis/data/processed/cleaned_order_items.csv')
cleaned_products = pd.read_csv(r'C:/Users/ASUS/OneDrive/Desktop/izaan_coding/project/customer-retention-analysis/data/processed/cleaned_products.csv')

In [90]:
print(cleaned_orders['order_id'].is_unique)       
print(cleaned_customers['customer_id'].is_unique)  
print(cleaned_products['product_id'].is_unique)

True
True
True

In [91]:
cleaned_orders['order_date'] = pd.to_datetime(cleaned_orders['order_date'])
cleaned_customers['signup_date'] = pd.to_datetime(cleaned_customers['signup_date'])

In [102]:
n = len(cleaned_order_items)

master = cleaned_order_items.merge(cleaned_orders, on='order_id', how='left')
assert len(master) == n, "orders join me rows badh gayi"

master = master.merge(cleaned_products, on='product_id', how='left')
assert len(master) == n, "products join me rows badh gayi"

master = master.merge(cleaned_customers, on='customer_id', how='left')
assert len(master) == n, "customers join me rows badh gayi"

In [103]:
print(master['customer_id'].isna().sum(),
      master['category'].isna().sum(),
      master['signup_date'].isna().sum())

0 0 0

In [104]:
master['line_revenue'] = master['quantity'] * master['unit_price'] - master['discount_amount']
master['order_month'] = master['order_date'].dt.to_period('M')

In [105]:
sales = master[master['status'] == 'completed'].copy()

In [107]:
print(len(master), len(sales))
print(round(sales['line_revenue'].sum(), 2))

15608 14283
1882076.88

In [108]:
master.to_csv(r'C:/Users/ASUS/OneDrive/Desktop/izaan_coding/project/customer-retention-analysis/data/processed/master_all.csv', index=False)
sales.to_csv(r'C:/Users/ASUS/OneDrive/Desktop/izaan_coding/project/customer-retention-analysis/data/processed/sales_completed.csv', index=False)