# "Kaun se customers valuable hain, kaun jaa rahe hain, aur unhe kaise roke?"

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
cleaned_customers = pd.read_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\cleaned_customers.csv',parse_dates=['signup_date'])

In [6]:
cleaned_customers.dtypes

customer_id                     int64
signup_date            datetime64[ns]
state                          object
acquisition_channel            object
dtype: object

In [7]:
cleaned_orders = pd.read_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\cleaned_orders.csv',parse_dates=['order_date'])

In [8]:
cleaned_orders.dtypes

order_id                   int64
customer_id                int64
order_date        datetime64[ns]
status                    object
payment_method            object
discount_code             object
shipping_fee             float64
dtype: object

In [9]:
cleaned_order_items = pd.read_csv(r'C:/Users/ASUS/OneDrive/Desktop/izaan_coding/project/customer-retention-analysis/data/processed/cleaned_order_items.csv')
cleaned_products = pd.read_csv(r'C:/Users/ASUS/OneDrive/Desktop/izaan_coding/project/customer-retention-analysis/data/processed/cleaned_products.csv')

In [10]:
sales = pd.read_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\sales_completed.csv')

In [11]:
sales.head()

,order_id,product_id,quantity,unit_price,discount_amount,customer_id,order_date,status,payment_method,discount_code,shipping_fee,product_name,category,list_price,unit_cost,signup_date,state,acquisition_channel,line_revenue,order_month
0,100001,1031,1,38.99,0.0,1530,2024-01-01 09:24:45,completed,credit_card,NO DISCOUNT,6.95,Stoneware Soap Dispenser,Bath,38.99,20.19,2023-12-30,AZ,organic_search,38.99,2024-01
1,100002,1087,1,45.99,0.0,3531,2024-01-01 10:37:49,completed,credit_card,NO DISCOUNT,0.00,Cotton Pantry Container Set,Storage,45.99,20.30,2023-11-19,VA,organic_search,45.99,2024-01
2,100002,1072,1,141.99,0.0,3531,2024-01-01 10:37:49,completed,credit_card,NO DISCOUNT,0.00,Coastal Picture Frame Set,Decor,141.99,62.78,2023-11-19,VA,organic_search,141.99,2024-01
3,100003,1048,1,139.99,0.0,840,2024-01-01 10:59:09,completed,credit_card,NO DISCOUNT,0.00,Linen Loveseat,Furniture,139.99,71.41,2023-10-30,MN,organic_search,139.99,2024-01
4,100004,1083,1,19.99,2.0,725,2024-01-01 12:48:34,completed,apple_pay,WELCOME10,0.00,Velvet Drawer Organizer,Storage,19.99,9.51,2023-08-20,MI,paid_search,17.99,2024-01

In [12]:
len(sales)

14283

In [13]:
sales['line_revenue'].sum()

np.float64(1882076.88)

In [14]:
sales['signup_date'] = pd.to_datetime(sales['signup_date'])

In [15]:
sales['order_date'] = pd.to_datetime(sales['order_date'])

In [16]:
sales.dtypes

order_id                        int64
product_id                      int64
quantity                        int64
unit_price                    float64
discount_amount               float64
customer_id                     int64
order_date             datetime64[ns]
status                         object
payment_method                 object
discount_code                  object
shipping_fee                  float64
product_name                   object
category                       object
list_price                    float64
unit_cost                     float64
signup_date            datetime64[ns]
state                          object
acquisition_channel            object
line_revenue                  float64
order_month                    object
dtype: object

In [17]:
cust_summary = sales.groupby('customer_id').agg(total_revenue = ('line_revenue','sum'),num_orders=('order_id','nunique'),first_order =('order_date','min'),last_order = ('order_date','max')).reset_index()

In [18]:
cust_summary

,customer_id,total_revenue,num_orders,first_order,last_order
0,2,130.19,1,2025-12-19 21:09:56,2025-12-19 21:09:56
1,4,258.98,1,2024-07-03 08:52:23,2024-07-03 08:52:23
2,5,1383.14,6,2025-05-08 18:38:32,2025-12-25 06:10:21
3,6,456.69,2,2025-11-02 13:45:09,2025-12-05 07:09:17
4,7,140.98,1,2024-10-31 11:04:33,2024-10-31 11:04:33
...,...,...,...,...,...
2042,3594,556.49,1,2025-10-19 08:49:26,2025-10-19 08:49:26
2043,3595,693.22,4,2025-05-25 21:15:45,2025-11-05 13:31:21
2044,3597,445.17,2,2025-11-21 18:07:01,2025-12-20 07:22:05
2045,3598,2017.85,9,2024-06-14 11:55:36,2024-10-04 23:51:22
2046,3600,474.55,4,2025-01-16 22:53:18,2025-03-30 22:45:45

In [19]:
cust_summary.to_csv(r'C:/Users/ASUS/OneDrive/Desktop/izaan_coding/project/customer-retention-analysis/data/processed/cust_sumary.csv', index=False)

In [20]:
len(cust_summary)

2047

In [21]:
cust_summary['total_revenue'].sum()

np.float64(1882076.88)

In [22]:
cust_summary['num_orders'].sum() ==sales['order_id'].nunique()

np.True_

# Revenue concentration.
### Business kitne customers par tika hai?

In [23]:
cust_summary = cust_summary.sort_values(by='total_revenue',ascending=False)

In [24]:
total_revenue_sum = cust_summary['total_revenue'].sum()
total_revenue_sum

np.float64(1882076.88)

In [25]:
n = int(cust_summary['customer_id'].count()*.2)
n

409

In [26]:
top20_revenue = cust_summary.head(n)['total_revenue'].sum()

In [27]:
shareof_top20 = (top20_revenue / total_revenue_sum) * 100

In [28]:
shareof_top20

np.float64(62.024905698857545)

In [29]:
top10_revenue = cust_summary.head(int(cust_summary['customer_id'].count()*.1))['total_revenue'].sum()
shareof_top10 = (top10_revenue / total_revenue_sum) * 100

In [30]:
print(f"top 10 % :- {round(shareof_top10)}  top 20 %:- {round(shareof_top20)}")

top 10 % :- 44  top 20 %:- 62

In [31]:
top50_revenue = cust_summary.head(int(cust_summary['customer_id'].count()*.5))['total_revenue'].sum()
shareof_top50 = (top50_revenue / total_revenue_sum) * 100

print(round(shareof_top50))

89

In [32]:
top80_revenue = cust_summary.head(int(cust_summary['customer_id'].count()*.8))['total_revenue'].sum()
top80_cust = cust_summary.head(int(cust_summary['customer_id'].count() * .8))['customer_id'].count()
print(top80_cust , top80_revenue)

1637 1849313.36

### "Top 20% customers 62% revenue laate hain, isliye in customers ko khona sabse mehnga padega."

## sirf top 5% customers ko sambhalna kaafi nahi hoga, retention ka kaam ek bade segment par karna padega.

In [33]:
cust_summary['cumulative revenue'] = cust_summary['total_revenue'].cumsum()

cust_summary['cum%'] = cust_summary['cumulative revenue'] / total_revenue_sum
customer_80_count = (cust_summary['cum%'] < 0.8).sum() + 1


print ( f"customer pecentage that contribute 80% in revenue is:- {int((customer_80_count/cust_summary['customer_id'].count())*100)}%")

customer pecentage that contribute 80% in revenue is:- 36%

In [34]:
cust_summary.tail()

,customer_id,total_revenue,num_orders,first_order,last_order,cumulative revenue,cum%
1253,2190,8.39,1,2025-02-03 22:44:29,2025-02-03 22:44:29,1882045.32,0.999983
385,669,8.39,1,2025-03-13 17:45:36,2025-03-13 17:45:36,1882053.71,0.999988
436,768,8.39,1,2025-08-28 13:03:57,2025-08-28 13:03:57,1882062.10,0.999992
873,1528,8.39,1,2025-12-17 23:38:36,2025-12-17 23:38:36,1882070.49,0.999997
289,500,6.39,1,2024-12-22 13:51:33,2024-12-22 13:51:33,1882076.88,1.000000

# Repeat purchase rate

# Kitne customers ek baar khareed ke wapas nahi aate?" Ye aapki business problem ka seedha number hai.

In [35]:
cust_summary['num_orders'].value_counts().sort_index()

num_orders
1     729
2     397
3     249
4     162
5     101
6      77
7      65
8      47
9      32
10     28
11     30
12     22
13     11
14     16
15      6
16     11
17      3
18      5
19      5
20      7
21      3
22      2
23      1
24      1
25      2
26      5
27      2
28      5
29      2
30      1
31      1
32      2
34      4
37      1
38      1
39      1
44      1
49      1
51      1
53      1
55      1
66      1
70      1
72      1
73      1
75      1
Name: count, dtype: int64

In [36]:
on_time = len(cust_summary [ cust_summary['num_orders']==1])

In [37]:
repeat = len(cust_summary[cust_summary['num_orders'] >=2])

In [38]:
(repeat / len(cust_summary)) *100

64.38690766976063

In [39]:
repeat_cust_per_in_revenue = (cust_summary[cust_summary['num_orders']>= 2]['total_revenue'].sum() / total_revenue_sum )*100

print(f"{int(repeat_cust_per_in_revenue)} %")

92 %

In [40]:
(cust_summary['total_revenue'][cust_summary['num_orders']== 1].sum() / total_revenue_sum) * 100

np.float64(7.839704720245011)

In [41]:
total_revenue_sum

np.float64(1882076.88)

# Repeat customers 64% hain lekin 92% revenue laate hain, isliye retention ka kaam inhi ko rokne par hona chahiye.

In [42]:
(cust_summary[cust_summary['num_orders']>= 2]['total_revenue'].sum())+(cust_summary[cust_summary['num_orders']== 1]['total_revenue'].sum() ) == total_revenue_sum

np.True_

In [43]:
cleaned_orders[cleaned_orders['status'] == 'canceled'].nunique()

order_id          344
customer_id       281
order_date        344
status              1
payment_method      4
discount_code       4
shipping_fee        2
dtype: int64

In [44]:
cust_without_purchase = (~(cleaned_customers['customer_id']).isin(cust_summary['customer_id'])).sum() / len(cleaned_customers) * 100

print(f"there is { int(cust_without_purchase)}% customer with no purchase")

there is 43% customer with no purchase

In [45]:
print(len(cust_summary),
len(cleaned_customers))

2047 3600

In [50]:
cust_summary_sorted = cust_summary.sort_values(by=
                                               'total_revenue', ascending=False)

In [51]:
cust_summary_sorted

,customer_id,total_revenue,num_orders,first_order,last_order,cumulative revenue,cum%
2004,3531,18775.23,70,2024-01-01 10:37:49,2025-02-04 16:12:37,18775.23,0.009976
885,1552,16740.67,73,2024-04-18 07:44:51,2025-10-16 09:33:40,35515.90,0.018871
623,1104,16071.59,75,2024-08-05 14:06:45,2025-06-21 10:52:02,51587.49,0.027410
27,48,15544.86,72,2024-02-03 11:27:07,2025-12-16 22:23:18,67132.35,0.035669
1601,2821,15535.41,66,2024-05-13 21:56:46,2025-05-21 22:37:19,82667.76,0.043924
...,...,...,...,...,...,...,...
1253,2190,8.39,1,2025-02-03 22:44:29,2025-02-03 22:44:29,1882045.32,0.999983
436,768,8.39,1,2025-08-28 13:03:57,2025-08-28 13:03:57,1882062.10,0.999992
385,669,8.39,1,2025-03-13 17:45:36,2025-03-13 17:45:36,1882053.71,0.999988
873,1528,8.39,1,2025-12-17 23:38:36,2025-12-17 23:38:36,1882070.49,0.999997
289,500,6.39,1,2024-12-22 13:51:33,2024-12-22 13:51:33,1882076.88,1.000000

In [61]:
rows =[]
for p in range(0, 101): 
    n = int(len(cust_summary_sorted) *( p / 100))
    rev = (cust_summary_sorted['total_revenue'].head(n).sum() / total_revenue_sum) *100
    rows.append((p,rev))

[(0, np.float64(0.0)), (1, np.float64(11.69961558637286)), (2, np.float64(17.974455432447588)), (3, np.float64(23.031260550844234)), (4, np.float64(26.978327792858288)), (5, np.float64(30.607994610719626)), (6, np.float64(33.74751248206184)), (7, np.float64(36.77730210468342)), (8, np.float64(39.40801026151493)), (9, np.float64(41.94627532962416)), (10, np.float64(44.20394293351078)), (11, np.float64(46.431693056024365)), (12, np.float64(48.435796097766215)), (13, np.float64(50.43207852380611)), (14, np.float64(52.2476079723162)), (15, np.float64(54.088897792528)), (16, np.float64(55.77235824712964)), (17, np.float64(57.38630560086367)), (18, np.float64(59.02552769257758)), (19, np.float64(60.51961596807885)), (20, np.float64(62.024905698857545)), (21, np.float64(63.4123160792454)), (22, np.float64(64.83003127906231)), (23, np.float64(66.12871786619047)), (24, np.float64(67.41724918272202)), (25, np.float64(68.60502265986075)), (26, np.float64(69.80834013539341)), (27, np.float64(70.92292903571507)), (28, np.float64(72.05528979241275)), (29, np.float64(73.10932643729198)), (30, np.float64(74.17609582452339)), (31, np.float64(75.1474961001593)), (32, np.float64(76.12064072536718)), (33, np.float64(77.0161880953556)), (34, np.float64(77.88824970848164)), (35, np.float64(78.77251486134827)), (36, np.float64(79.58779080267966)), (37, np.float64(80.42607749371004)), (38, np.float64(81.19704121757239)), (39, np.float64(81.98845150257624)), (40, np.float64(82.71667414563852)), (41, np.float64(83.4582851897102)), (42, np.float64(84.13654281752827)), (43, np.float64(84.8278976786538)), (44, np.float64(85.46178304894751)), (45, np.float64(86.10555324392489)), (46, np.float64(86.69783457517423)), (47, np.float64(87.30511635635204)), (48, np.float64(87.8614028774425)), (49, np.float64(88.42937117425299)), (50, np.float64(88.95678852396294)), (51, np.float64(89.46792970540078)), (52, np.float64(89.9816127596233)), (53, np.float64(90.45159037286511)), (54, np.float64(90.92785465809452)), (55, np.float64(91.36187996741133)), (56, np.float64(91.79279913368897)), (57, np.float64(92.1900751471959)), (58, np.float64(92.59112093231813)), (59, np.float64(92.95851984537423)), (60, np.float64(93.33057372236568)), (61, np.float64(93.66927561428841)), (62, np.float64(94.01380776751267)), (63, np.float64(94.32962695976586)), (64, np.float64(94.65055752664047)), (65, np.float64(94.94600720030098)), (66, np.float64(95.24318687767952)), (67, np.float64(95.51470288503836)), (68, np.float64(95.77667677422403)), (69, np.float64(96.04310531671798)), (70, np.float64(96.28368369309122)), (71, np.float64(96.52448469586429)), (72, np.float64(96.7451223352789)), (73, np.float64(96.96898726049918)), (74, np.float64(97.17420045030254)), (75, np.float64(97.38145393933112)), (76, np.float64(97.56939259569461)), (77, np.float64(97.75900227837666)), (78, np.float64(97.93150479591462)), (79, np.float64(98.10306154974924)), (80, np.float64(98.25918269608627)), (81, np.float64(98.41760289834707)), (82, np.float64(98.56111350775424)), (83, np.float64(98.70534300384158)), (84, np.float64(98.835786134305)), (85, np.float64(98.95847719036854)), (86, np.float64(99.07932294455473)), (87, np.float64(99.18697848304687)), (88, np.float64(99.29179513644524)), (89, np.float64(99.3853428559199)), (90, np.float64(99.4767822661952)), (91, np.float64(99.55831400468614)), (92, np.float64(99.63881762364565)), (93, np.float64(99.70726488069924)), (94, np.float64(99.77273882669448)), (95, np.float64(99.8303809991014)), (96, np.float64(99.88403396146072)), (97, np.float64(99.92617517303545)), (98, np.float64(99.96193513625224)), (99, np.float64(99.98504896356839)), (100, np.float64(100.0))]

In [62]:
pbi_data = pd.DataFrame(rows,columns=['customer_pct','revenue_pct'])

In [65]:
pbi_data.head()
print(len(pbi_data))

101

In [66]:
pbi_data.to_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\pbi_data.csv',index=False)