In [1]:
import pandas as pd 
import numpy as np

In [2]:
cleaned_customers = pd.read_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\cleaned_customers.csv',parse_dates=['signup_date'])

In [3]:
cleaned_orders = pd.read_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\cleaned_orders.csv',parse_dates=['order_date'])

In [4]:
cleaned_order_items = pd.read_csv(r'C:/Users/ASUS/OneDrive/Desktop/izaan_coding/project/customer-retention-analysis/data/processed/cleaned_order_items.csv')
cleaned_products = pd.read_csv(r'C:/Users/ASUS/OneDrive/Desktop/izaan_coding/project/customer-retention-analysis/data/processed/cleaned_products.csv')

In [5]:
sales = pd.read_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\sales_completed.csv')

In [6]:
cust_summary = pd.read_csv(r'C:/Users/ASUS/OneDrive/Desktop/izaan_coding/project/customer-retention-analysis/data/processed/cust_sumary.csv')

In [7]:
cust_summary.dtypes

customer_id             int64
total_revenue         float64
num_orders              int64
first_order            object
last_order             object
cumulative revenue    float64
cum%                  float64
dtype: object

## RFM segmentation

In [8]:
cust_summary['first_order'] = pd.to_datetime(cust_summary['first_order'])
cust_summary['last_order'] = pd.to_datetime(cust_summary['last_order'])

In [9]:
cust_summary.dtypes

customer_id                    int64
total_revenue                float64
num_orders                     int64
first_order           datetime64[ns]
last_order            datetime64[ns]
cumulative revenue           float64
cum%                         float64
dtype: object

In [10]:
cust_summary.head()

,customer_id,total_revenue,num_orders,first_order,last_order,cumulative revenue,cum%
0,3531,18775.23,70,2024-01-01 10:37:49,2025-02-04 16:12:37,18775.23,0.009976
1,1552,16740.67,73,2024-04-18 07:44:51,2025-10-16 09:33:40,35515.90,0.018871
2,1104,16071.59,75,2024-08-05 14:06:45,2025-06-21 10:52:02,51587.49,0.027410
3,48,15544.86,72,2024-02-03 11:27:07,2025-12-16 22:23:18,67132.35,0.035669
4,2821,15535.41,66,2024-05-13 21:56:46,2025-05-21 22:37:19,82667.76,0.043924

In [11]:
sales.dtypes

order_id                 int64
product_id               int64
quantity                 int64
unit_price             float64
discount_amount        float64
customer_id              int64
order_date              object
status                  object
payment_method          object
discount_code           object
shipping_fee           float64
product_name            object
category                object
list_price             float64
unit_cost              float64
signup_date             object
state                   object
acquisition_channel     object
line_revenue           float64
order_month             object
dtype: object

In [12]:
sales['order_date'] = pd.to_datetime(sales['order_date'])

In [13]:
sales.head()

,order_id,product_id,quantity,unit_price,discount_amount,customer_id,order_date,status,payment_method,discount_code,shipping_fee,product_name,category,list_price,unit_cost,signup_date,state,acquisition_channel,line_revenue,order_month
0,100001,1031,1,38.99,0.0,1530,2024-01-01 09:24:45,completed,credit_card,NO DISCOUNT,6.95,Stoneware Soap Dispenser,Bath,38.99,20.19,2023-12-30,AZ,organic_search,38.99,2024-01
1,100002,1087,1,45.99,0.0,3531,2024-01-01 10:37:49,completed,credit_card,NO DISCOUNT,0.00,Cotton Pantry Container Set,Storage,45.99,20.30,2023-11-19,VA,organic_search,45.99,2024-01
2,100002,1072,1,141.99,0.0,3531,2024-01-01 10:37:49,completed,credit_card,NO DISCOUNT,0.00,Coastal Picture Frame Set,Decor,141.99,62.78,2023-11-19,VA,organic_search,141.99,2024-01
3,100003,1048,1,139.99,0.0,840,2024-01-01 10:59:09,completed,credit_card,NO DISCOUNT,0.00,Linen Loveseat,Furniture,139.99,71.41,2023-10-30,MN,organic_search,139.99,2024-01
4,100004,1083,1,19.99,2.0,725,2024-01-01 12:48:34,completed,apple_pay,WELCOME10,0.00,Velvet Drawer Organizer,Storage,19.99,9.51,2023-08-20,MI,paid_search,17.99,2024-01

In [14]:
snapshot_date = sales['order_date'].max() +pd.Timedelta(days=1)
snapshot_date

Timestamp('2026-01-01 23:23:29')

In [15]:
recency = (snapshot_date - cust_summary['last_order']).dt.days
recency

0       331
1        77
2       194
3        16
4       225
       ...
2042    332
2043    294
2044    126
2045     14
2046    375
Name: last_order, Length: 2047, dtype: int64

In [16]:
cust_summary['recency'] = recency

In [17]:
cust_summary.head(12)

,customer_id,total_revenue,num_orders,first_order,last_order,cumulative revenue,cum%,recency
0,3531,18775.23,70,2024-01-01 10:37:49,2025-02-04 16:12:37,18775.23,0.009976,331
1,1552,16740.67,73,2024-04-18 07:44:51,2025-10-16 09:33:40,35515.90,0.018871,77
2,1104,16071.59,75,2024-08-05 14:06:45,2025-06-21 10:52:02,51587.49,0.027410,194
3,48,15544.86,72,2024-02-03 11:27:07,2025-12-16 22:23:18,67132.35,0.035669,16
4,2821,15535.41,66,2024-05-13 21:56:46,2025-05-21 22:37:19,82667.76,0.043924,225
5,3069,12335.39,49,2024-02-29 21:43:58,2025-08-10 17:55:36,95003.15,0.050478,144
6,443,12207.45,53,2024-04-21 22:27:48,2025-12-18 06:07:52,107210.60,0.056964,14
7,307,11775.84,51,2024-01-03 17:53:45,2025-12-08 14:18:39,118986.44,0.063221,24
8,2577,10344.24,55,2024-01-03 07:02:06,2025-12-29 17:52:07,129330.68,0.068717,3
9,1454,9954.31,34,2024-01-12 07:11:58,2025-08-06 20:05:41,139284.99,0.074006,148
10,135,9509.43,38,2024-06-09 22:03:42,2025-11-29 07:32:13,148794.42,0.079059,33
11,3114,9102.53,32,2024-01-05 10:38:55,2024-07-12 08:48:46,157896.95,0.083895,538

In [18]:
cust_summary[['recency', 'num_orders', 'total_revenue']].describe()

           recency   num_orders  total_revenue
count  2047.000000  2047.000000    2047.000000
mean    196.222277     4.130923     919.431793
std     183.420048     6.185109    1451.287375
min       1.000000     1.000000       6.390000
25%      37.000000     1.000000     180.970000
50%     136.000000     2.000000     489.250000
75%     315.500000     4.000000    1095.585000
max     723.000000    75.000000   18775.230000

In [19]:
labels=[4,3,2,1]

In [20]:
r_score = pd.qcut(recency,q=4,labels=labels)
r_score

0       1
1       3
2       2
3       4
4       2
       ..
2042    1
2043    2
2044    3
2045    4
2046    1
Name: last_order, Length: 2047, dtype: category
Categories (4, int64): [4 < 3 < 2 < 1]

In [21]:
f_score = pd.cut(
    cust_summary['num_orders'],
    bins=[0, 1, 2, 4, np.inf],
    labels=[1, 2, 3, 4]
).astype(int)
f_score

0       4
1       4
2       4
3       4
4       4
       ..
2042    1
2043    1
2044    1
2045    1
2046    1
Name: num_orders, Length: 2047, dtype: int64

In [22]:
m_score = pd.qcut(cust_summary['total_revenue'],q=4,labels=[1,2,3,4])
m_score

0       4
1       4
2       4
3       4
4       4
       ..
2042    1
2043    1
2044    1
2045    1
2046    1
Name: total_revenue, Length: 2047, dtype: category
Categories (4, int64): [1 < 2 < 3 < 4]

In [23]:
cust_summary['f_score'] = f_score

In [24]:
cust_summary['m_score'] = m_score
cust_summary['r_score'] = r_score

In [25]:
cust_summary.head(20)

,customer_id,total_revenue,num_orders,first_order,last_order,cumulative revenue,cum%,recency,f_score,m_score,r_score
0,3531,18775.23,70,2024-01-01 10:37:49,2025-02-04 16:12:37,18775.23,0.009976,331,4,4,1
1,1552,16740.67,73,2024-04-18 07:44:51,2025-10-16 09:33:40,35515.90,0.018871,77,4,4,3
2,1104,16071.59,75,2024-08-05 14:06:45,2025-06-21 10:52:02,51587.49,0.027410,194,4,4,2
3,48,15544.86,72,2024-02-03 11:27:07,2025-12-16 22:23:18,67132.35,0.035669,16,4,4,4
4,2821,15535.41,66,2024-05-13 21:56:46,2025-05-21 22:37:19,82667.76,0.043924,225,4,4,2
5,3069,12335.39,49,2024-02-29 21:43:58,2025-08-10 17:55:36,95003.15,0.050478,144,4,4,2
6,443,12207.45,53,2024-04-21 22:27:48,2025-12-18 06:07:52,107210.60,0.056964,14,4,4,4
7,307,11775.84,51,2024-01-03 17:53:45,2025-12-08 14:18:39,118986.44,0.063221,24,4,4,4
8,2577,10344.24,55,2024-01-03 07:02:06,2025-12-29 17:52:07,129330.68,0.068717,3,4,4,4
9,1454,9954.31,34,2024-01-12 07:11:58,2025-08-06 20:05:41,139284.99,0.074006,148,4,4,2
10,135,9509.43,38,2024-06-09 22:03:42,2025-11-29 07:32:13,148794.42,0.079059,33,4,4,4
11,3114,9102.53,32,2024-01-05 10:38:55,2024-07-12 08:48:46,157896.95,0.083895,538,4,4,1
12,3452,9015.68,31,2024-01-01 17:44:03,2025-11-30 13:09:14,166912.63,0.088685,32,4,4,4
13,1375,8250.36,28,2024-01-08 11:28:48,2025-04-18 10:16:53,175162.99,0.093069,258,4,4,2
14,572,8174.50,34,2024-01-02 15:20:47,2024-05-27 22:17:41,183337.49,0.097412,584,4,4,1
15,2743,7864.06,44,2024-09-19 21:41:20,2025-12-08 18:00:05,191201.55,0.101591,24,4,4,4
16,2221,7586.78,30,2024-01-02 18:56:18,2024-05-25 20:48:23,198788.33,0.105622,586,4,4,1
17,1443,7148.84,26,2024-06-07 16:02:03,2025-12-11 23:24:26,205937.17,0.109420,20,4,4,4
18,115,7135.87,34,2024-03-17 21:34:05,2025-05-22 13:18:16,213073.04,0.113212,224,4,4,2
19,1891,7122.72,34,2024-01-03 14:35:26,2025-11-25 16:43:50,220195.76,0.116996,37,4,4,4

In [26]:
cust_summary['r_score'].value_counts()

r_score
4    514
3    512
1    512
2    509
Name: count, dtype: int64

In [27]:
cust_summary['m_score'].value_counts()

m_score
1    513
4    512
2    511
3    511
Name: count, dtype: int64

In [28]:
cust_summary['f_score'].value_counts()

f_score
1    729
4    510
3    411
2    397
Name: count, dtype: int64

In [29]:
cust_summary.groupby('f_score')['num_orders'].agg(['min', 'max'])

         min  max
f_score
1          1    1
2          2    2
3          3    4
4          5   75

In [30]:
r = cust_summary['r_score'].astype(int)
f = cust_summary['f_score'].astype(int)
m = cust_summary['m_score'].astype(int)

conditions = [
    (r == 4) & (f >= 3) & (m >= 3),
    (r >= 3) & (f >= 2),
    (r >= 3) & (f == 1),
    (r <= 2) & (f >= 2),
    (r <= 2) & (f == 1)
]

labels = ["Champions", "Loyal", "New", "At-Risk", "Lost"]
cust_summary['segment'] = np.select(conditions, labels, default='Unassigned')

In [31]:
cust_summary['segment'].isna().sum()

np.int64(0)

In [32]:
print(cust_summary['segment'].value_counts())
print(cust_summary['segment'].isna().sum())

segment
At-Risk      618
Loyal        465
Lost         403
New          326
Champions    235
Name: count, dtype: int64
0

In [47]:
 v=cust_summary.groupby('segment').agg(
    total_cus = ('customer_id','count'),
    total_rev = ('total_revenue','sum'),
    avg_rev = ('total_revenue','mean'), 
    avg_recency = ('recency','mean'),
    avg_num_orders = ('num_orders','mean')
 )  
v['revenue_pct'] = round((v['total_rev'] / v['total_rev'].sum()) * 100)
v

,total_cus,total_rev,avg_rev,avg_recency,avg_num_orders,revenue_pct
segment,,,,,,
At-Risk,618,802600.66,1298.706570,342.865696,5.690939,43.0
Champions,235,475095.21,2021.681745,20.255319,9.182979,25.0
Lost,403,80566.39,199.916600,343.880893,1.000000,4.0
Loyal,465,456831.74,982.433849,63.836559,4.412903,24.0
New,326,66982.88,205.468957,51.374233,1.000000,4.0

In [44]:
v['total_rev'].sum()
v['total_cus'].sum()

np.int64(2047)

In [34]:
print(cust_summary.groupby('r_score')['recency'].agg(['min', 'max', 'count']))

         min  max  count
r_score
4          1   37    514
3         38  136    512
2        137  315    509
1        316  723    512

C:\Users\ASUS\AppData\Local\Temp\ipykernel_3268\2447950766.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(cust_summary.groupby('r_score')['recency'].agg(['min', 'max', 'count']))

In [35]:
print(pd.crosstab(cust_summary['segment'], cust_summary['r_score']))

r_score      4    3    2    1
segment
At-Risk      0    0  313  305
Champions  235    0    0    0
Lost         0    0  196  207
Loyal      132  333    0    0
New        147  179    0    0

In [48]:
cust_summary.to_csv(r'C:\Users\ASUS\OneDrive\Desktop\izaan_coding\project\customer-retention-analysis\data\processed\customer_segments.csv',index=False)